### ISSUE TITLE
Seems to be incompatible with the new Angular 6.

### ISSUE THREAD

**Issue by larssn** [mattlewis92/angular-async-cache#5]
Without digging too much, I think it's the `isObservable` call thats causing problems, as it's using `Symbol.observable` which apparently doesn't work.

See https://github.com/benlesh/symbol-observable/issues/38

**Comment by sconix** [comment]
Would be nice to get update that supports rxjs 6 so we do not need to use the compat library. In our project this is the only library that needs it.

**Comment by mattlewis92** [comment]
This is now done in `2.0.0`, thanks for your patience! 😄
